### ISSUE TITLE
[FEAT] 애플로그인 환경 설정/구현 

### ISSUE THREAD

**Issue by yerim216** [NZ-generation/WhereRU-server#1]
## Description
- 앱스토어 출시를 위한 애플 로그인 기능을 구현합니다

## To-do
- 상세 작업 내용을 적어주세요
- [x] 애플 로그인 관련 환경 설정
- [x] 로그인/회원가입 관련 security 설정
- [x] 로그인/회원가입 기능 구현 
- [x] CurrentUser 어노테이션 구현
