### ISSUE TITLE
[FEAT] 회원정보 관련 API 구현

### ISSUE THREAD

**Issue by yerim216** [NZ-generation/WhereRU-server#10]
## Description
- 회원정보 관련 API를 구현합니다

## To-do
- 상세 작업 내용을 적어주세요
- [x] 닉네임 중복 확인
- [x] 닉네임 수정
- [x] 지갑주소 수정
- [x] OO님, N일 째 환경 보호 중! (가입 한지 며칠 째인지 계산)
- [x] 보유 포인트 조회
- [x] 보유 뱃지, NFT 갯수 조회
- [x] 프로필 사진 편집
- [x] 회원 정보 조회하기
- [x] 회원 정보 편집하기(조회 화면)
