### ISSUE TITLE
[FEAT] 관리자 페이지 api 

### ISSUE THREAD

**Issue by gourderased** [NZ-generation/WhereRU-server#25]
## To-do
- 회원 관리 
- 쓰레기통 관리

## api

- [x] 제보 횟수, 오류 제보 횟수 조회
```
{
    "제보횟수" : 3,
    "오류 제호 횟수 : 5,
    "revenue": [
        105.29803463863626,
        83.49399386011865,
        180.73928852958973,
        -34.76397015594929,
        228.43739447102274,
        120.84113594981993
    ],
    "month": [
        "2022-12-01",
        "2022-11-01",
        "2022-10-01",
        "2022-09-01",
        "2022-08-01",
        "2022-07-01"
    ]
}
```
- [ ] 쓰레기통 월별 개수 조회
```
{
    "Enterprise" : 9,
    "Basic" : 3,
    "Pro" : 5
}
```
- [ ] 쓰레기통 승인/거절
- [ ] 쓰레기통 목록 조회
